### ISSUE TITLE
Feature request: disable parent with disabled stock in purchase dialog

### ISSUE THREAD

**Issue by Saturo78** [patzly/grocy-android#606] opened 2022-12-24 08:59 UTC
The purchase dialog shows also parent products with "disable own stock"

Instead of this i would find it very helpful when in the case of buying such a parent (because it is used in a recipe) the valid childs are shown in the purchase dialog.

**Comment by dominiczedler** [comment] 2022-12-25 14:47
I think this is a duplicate of #508. I think I can implement this right now quickly.

**Closed by dominiczedler** 2022-12-25 14:47 UTC

**Comment by dominiczedler** [comment] 2022-12-25 15:19
There is now a selection for child products implemented, if the selected parent product has no own stock.
