### ISSUE TITLE
Master Products: Use OpenFoodFact for new products with barcode

### ISSUE THREAD

**Issue by asdrolf** [patzly/grocy-android#232] opened 2020-11-09 18:35 UTC
when i scan a code on consume screen it automatically loads the name of the profuct (wich is not added to database) so it says no valid product. but when i try to add the product on add screen it doesnt load the name. i m doing something wrong?

**Comment by MrJohnZoidberg** [comment] 2020-11-09 21:56
Sorry, I don't understand which screen you mean: the purchase & consume screen with the form or the screen of the batch mode?

**Comment by MrJohnZoidberg** [comment] 2020-11-10 18:38
Sorry, your answer contains the same (still not enough) information but only in other words. Can you please provide screenshots? I still cannot reproduce this, because I don't understand what screens you mean and what extact steps you are doing. Please write me some structured steps, like this:

1. First step
(Screenshot)
2. Second step
(screenshot)
3. And so on

And please try to write real English and not without any upper case or punctuation.

**Comment by radim-ek** [comment] 2020-11-10 21:05
If I understand well, OpenFactFood working in Batch Tools, but not in Add Product in Master Data.

**Comment by MrJohnZoidberg** [comment] 2020-11-11 20:41
Ah thanks for your help @radim-ek, I will change the headline.:+1:

**Comment by MrJohnZoidberg** [comment] 2021-04-25 12:39
I'm closing this one because the same thing is tracked in #353 .

**Closed by MrJohnZoidberg** 2021-04-25 12:39 UTC
Labels: enhancement
