### ISSUE TITLE
App crash when viewing a product

### ISSUE THREAD

**Issue by albarreto** [patzly/grocy-android#701] opened 2023-05-20 20:50 UTC
--------- beginning of crash
05-20 17:48:42.685  6148  6148 E AndroidRuntime: FATAL EXCEPTION: main
05-20 17:48:42.685  6148  6148 E AndroidRuntime: Process: xyz.zedler.patrick.grocy, PID: 6148
05-20 17:48:42.685  6148  6148 E AndroidRuntime: java.lang.ClassCastException
05-20 17:48:42.685  6148  6148 E AndroidRuntime: 	at androidx.camera.core.impl.Config$-CC.m(SourceFile:34)
05-20 17:48:42.685  6148  6148 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.fragment.bottomSheetDialog.ProductOverviewBottomSheet$$ExternalSyntheticLambda2.onResponse(SourceFile:41)
05-20 17:48:42.685  6148  6148 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.helper.DownloadHelper$$ExternalSyntheticLambda7.onResponse(Unknown Source:9)
05-20 17:48:42.685  6148  6148 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.web.CustomStringRequest$$ExternalSyntheticLambda0.onResponse(SourceFile:27)
05-20 17:48:42.685  6148  6148 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.web.CustomStringRequest.deliverResponse(SourceFile:11)
05-20 17:48:42.685  6148  6148 E AndroidRuntime: 	at com.google.android.gms.common.images.zaa.run(SourceFile:210)
05-20 17:48:42.685  6148  6148 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
05-20 17:48:42.685  6148  6148 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-20 17:48:42.685  6148  6148 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:226)
05-20 17:48:42.685  6148  6148 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:313)
05-20 17:48:42.685  6148  6148 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8751)
05-20 17:48:42.685  6148  6148 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-20 17:48:42.685  6148  6148 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
05-20 17:48:42.685  6148  6148 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
--------- beginning of main
05-20 17:48:48.665  6893  6893 E r.patrick.groc: Not starting debugger since process cannot load the jdwp agent.
05-20 17:48:48.668  6893  6893 E USNET   : USNET: appName: xyz.zedler.patrick.grocy

**Comment by dominiczedler** [comment] 2023-05-20 20:57
Thank you for reporting! It's a duplicate of #699, I will close this one.

**Closed by dominiczedler** 2023-05-20 20:57 UTC
Labels: duplicate
