### ISSUE TITLE
Add support for Grocy 4.0.3

### ISSUE THREAD

**Issue by jahway603** [patzly/grocy-android#772] opened 2023-09-02 23:52 UTC
Running latest grocy-android release v 3.3.1 with a recently upgraded grocy server to v 4.0.3 & the app claims it is unsupported.

**Comment by bzar** [comment] 2023-09-03 05:49
This combination seems to have broken consuming products for some reason. Works on Web UI, getting

```
Network error

com.android.volley.ClientError
	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:251)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:51)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:6)
```

on android client.

**Comment by dominiczedler** [comment] 2023-09-04 20:43
I'm currently working on my bachelor thesis, sorry for the delays. I will look into it and hopefully a fix can be released in the next days... I can also reproduce the bug.

**Closed** 2023-09-05 20:08 UTC
Labels: bug, enhancement

**Comment by stuckinger** [comment] 2023-09-17 08:10
Hi! I know this issue is closed, but isn't the current version on f-droid still 3.3.1 which does not support 4.0.3 server version?
I am having the same issue. Is there a roadmap on bringing the version that's working with 4.0.3 server to f-droid soon?

**Comment by dominiczedler** [comment] 2023-09-17 11:45
@stuckinger There was an issue with a library version which is not supported by the build server. We have to release another version first, so that the build server has the updated library. In the meantime you could also use the GitHub APK downloads.

**Comment by patzly** [comment] 2023-09-17 13:14
If you use the GitHub download until we release a small update in one week, you sadly have to uninstall the F-Droid version first because the GitHub version uses the Google Play signature.

**Comment by stuckinger** [comment] 2023-09-18 16:54
Thanks for your reply!
@patzly: one week is enough for me as a "roadmap" ;-)
I just started with Grocy, so I can just wait another week and hope it will work smoothly with a new version from fdroid.
