### ISSUE TITLE
Wrong price calculation

### ISSUE THREAD

**Issue by Quantum1337** [patzly/grocy-android#578] opened 2022-09-29 14:02 UTC
Hello there,

there is a problem with setting the price out of the previous "learned" prices. I made a minimal example here:

[Demo](https://test-s40b848hte9637nvortzjg.demo.grocy.info/product/28)

The following Barcodes are used:

4063367330421 - Edam Pack (250g) 
4337185684982 - Edam Pack (400g)

In the WebUI it is correct:

![Bildschirmfoto vom 2022-09-29 15-47-14](https://user-images.githubusercontent.com/36477626/193050823-090fb037-e7db-4b7d-aeb2-c79aa0a95881.png)
![Bildschirmfoto vom 2022-09-29 15-47-45](https://user-images.githubusercontent.com/36477626/193050830-d2612b59-761b-48b2-95e6-3ee38d33352c.png)

The AppUI is showing the following (seems to be the mean price):

![Screenshot_20220929-154429_Grocy](https://user-images.githubusercontent.com/36477626/193051136-982410d3-b212-4272-8905-9b4ecfa099a0.png) 
![Screenshot_20220929-154515_Grocy](https://user-images.githubusercontent.com/36477626/193051142-37877054-79d0-48eb-b8bb-5f10724d050c.png)

Thanks you for this great app :)

**Comment by MrJohnZoidberg** [comment] 2022-10-24 20:09
Thanks for the screenshots and the demo, I hope the commit fixes the problem. :)

**Comment by yekteniya** [comment] 2023-07-21 20:32
I'm having this issue in version 3.2.1 (F-droid). The behavior is the same, where the web app does the price calculation properly but the Android app doesn't after a bar code is scanned when making a purchase. Please let me know if any proof is needed.

**Comment by dominiczedler** [comment] 2023-12-22 12:02
@yekteniya Can you please show me an example? This would be helpful for solving the issue, because I can't reproduce something with that.

**Comment by yekteniya** [comment] 2023-12-22 13:38
I believe the issue I had must have been due to some kind of incompatibility between the server and the app's version, since I haven't been able to reproduce this for quite some time now since I updated everything. So please, feel free to close this issue again.

**Comment by dominiczedler** [comment] 2023-12-22 14:18
Thanks, feel free to open any issue for bug fixing, I'm in mood right now to fix these annoying bugs concerning prices, units and so on.

**Closed by dominiczedler** 2023-12-22 14:18 UTC
Labels: bug, missing info
