### ISSUE TITLE
Add connection option for Local Lan and External connection.

### ISSUE THREAD

**Issue by asdrolf** [patzly/grocy-android#251] opened 2020-11-28 13:11 UTC
I have problems connecting to my instance of Grocy. (Installed with an addon of Home Assistant and using Duckdns , Letsencrypt and nginx) 

I' am using the Grocy Addon for Home Assistant with duckdns to access it from external web over SSL, and for local access I use the local IP (duckdns domain is not accesible from inside).  The Home Assistant app let you configure your wifi name and another url to connect if you are connected to this ssid so you can use local ip if you are connected to this wifi.

![3efd9102-ec7a-4b6e-aad3-89fadb449d7f](https://user-images.githubusercontent.com/39625370/100516304-32f00680-3183-11eb-82ef-66915e558f0f.jpg)

**Comment by radim-ek** [comment] 2020-11-28 16:16
As I understand well, you need a VALID SSL certificate for use it in Grocy for Android. So, without https (in your local lan) this app will not work. So this options is useless.

**Comment by MrJohnZoidberg** [comment] 2020-11-28 23:27
This is a duplicate of #53. Like you can see on the milestone of that issue, this feature has a low priority for us because we (the developers) don't need it and the app needs more permissions for accessing the Wifi SSID of the current Wifi.
And another reason is that we have full-time jobs now and therefore don't have the energy to work on features which are complicated and don't have a result for most users of the app.

> duckdns domain is not accesible from inside

That's weird because like when you are outside, the DynDNS service should still resolve the domain name into your public IP. And your public IP should be accessible from your local network, too...

@radim-ek No I'm sorry, that's not correct. You don't need a SSL certificate in a local network for our app. :-)

**Closed** 2020-11-28 23:27 UTC
Labels: duplicate
