### ISSUE TITLE
Stock overview filtering discrepancy

### ISSUE THREAD

**Issue by samnewman86** [patzly/grocy-android#352] opened 2021-02-12 18:40 UTC
Different stock is shown when filtering by location.
See screenshots
![Screenshot_20210212-183933](https://user-images.githubusercontent.com/53034649/107808617-cc31c080-6d61-11eb-87c4-f594b9d8a58c.jpg)
![Screenshot_20210212-183859](https://user-images.githubusercontent.com/53034649/107808619-ccca5700-6d61-11eb-9345-5103264f9f1a.jpg)

**Comment by MrJohnZoidberg** [comment] 2021-02-12 18:46
Thanks, but please look for open issues first. This is a duplicate of #248.

**Closed by MrJohnZoidberg** 2021-02-12 18:46 UTC
