### ISSUE TITLE
Offline mode not working properly on shopping mode page

### ISSUE THREAD

**Issue by Deldaflyer** [patzly/grocy-android#781] opened 2023-09-15 23:00 UTC
Hey all,

I recently started using Grocy (on my Home Assistant installation) and the Android app.
I also noticed that there is an offline mode, which is helpful, as my HA installation is not available from the Internet.

But I was expecting that I can mark items as bought in the Shopping list, while in Offline mode, but somehow that only works while I'm online.
Do I need to configure something additionally or does it just not work?

HA Grocy Addon Version: ~0.19.1~ 0.20.0
Grocy Android Version: ~3.3.1~ 3.3.2

kind regards,
Delta

**Comment by patzly** [comment] 2023-09-16 23:17
Do you mean marking items as "done" (strikethrough) or actually purchasing them? The marking as "done" feature should work fine in both online and offline mode.
Purchasing items while offline cannot be done without complications as there are many server-side checks required which simply doesn't make sense for a companion app of a server-based application. For me the behavior I use all day is: marking the items which are in my physical shopping bag as done without purchasing them in the app, and then go home and purchase them in the app. So I think the offline instance shouldn't be much of a problem.

**Comment by Deldaflyer** [comment] 2023-09-17 08:47
Hello patzly,

Yes, I was talking about striking them out in the Shopping Mode.
I also tried around a bit more and noticed that:
- if I have the Shopping Mode page open and then "go offline", striking out items is working. The Shopping Mode shows the red "Offline" status.
- if I navigate back to the main page and then reopening the Shopping Mode, striking out is not working.  The main page shows the red "Offline" status, but not not the Shopping Mode page.
- same happens if I freshly open the App while being offline.
- if I then navigate to the Shopping Mode and swipe down to refresh, after a few seconds the Offline status is shown again and I am able to strike out items. But the refresh icon is permanently shown on the screen.
- waiting for 10 seconds on the Shopping Mode page is showing the red Offline status, even after changeing the network timeout and update interval to 4 seconds.

Kind regards,
Delta

**Comment by eskahone** [comment] 2023-09-25 14:56
I can cofirm this behavior for a "normal" docker installation. 
However, if you stay on your shopping list and do not enter the shopping mode (while offline), you can strike out item by clicking on them and then select the check mark.
![IMG_20230925_165539](https://github.com/patzly/grocy-android/assets/74679226/cf6df209-86bb-49b6-a845-a05d13a32c1f)
This removes the item from the list and synchronizes as expected when going online again.

**Comment by dominiczedler** [comment] 2023-09-30 01:18
What does offline mean for you? When I disable wifi on my test smartphone without mobile data, the offline bar always appears on opening the page. The long loading circle may be a sign for a very bad internet connection, else I can't reproduce it now.

**Comment by dominiczedler** [comment] 2024-01-13 19:03
@alkuzman Thanks for the hint, yes this could be the case. I would say that it is the easiest way to merge this issue in #816 (manual offline mode for bad connections).

**Closed by dominiczedler** 2024-01-13 19:03 UTC
Labels: missing info
