### ISSUE TITLE
App crashes on barcode scanner and settings page opening

### ISSUE THREAD

**Issue by ivanboytsov** [patzly/grocy-android#118] opened 2020-09-27 16:44 UTC
After adding a lot of products into stock the app started crashing just after scanner and settings opening.
I already sent the logs via android bug reporting.
The app version is 1.8.7
Android 9
Samsung Galaxy J7

**Comment by ivanboytsov** [comment] 2020-09-28 05:41
If it will help, I can give api access key to my instance of grocy.

**Comment by ivanboytsov** [comment] 2020-09-28 13:20
![Screenshot_20200928-161943_Grocy](https://user-images.githubusercontent.com/70232503/94437537-91f6c680-01a6-11eb-9241-2f39245d2362.jpg)

**Comment by ivanboytsov** [comment] 2020-09-28 13:21
![Screenshot_20200928-162121_Grocy](https://user-images.githubusercontent.com/70232503/94437620-adfa6800-01a6-11eb-94a3-ded404d70d03.jpg)

**Comment by ivanboytsov** [comment] 2020-09-28 17:48
I found what caused the problems - very large product descriptions.

**Comment by MrJohnZoidberg** [comment] 2020-09-28 21:47
Mmh, thanks for reporting this – the app should not crash, even with large product descriptions.
And it is weird that the settings page crashes too, because there are no products loaded in this page...
I will reopen this and look over the logs which you've sent when I have enough time.

**Comment by afv** [comment] 2020-10-01 12:03
I'm having the same problem. Opening settings:

```10-01 12:58:08.291  2112  2112 E AndroidRuntime: FATAL EXCEPTION: main
10-01 12:58:08.291  2112  2112 E AndroidRuntime: Process: xyz.zedler.patrick.grocy, PID: 2112
10-01 12:58:08.291  2112  2112 E AndroidRuntime: java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 2618084 bytes
10-01 12:58:08.291  2112  2112 E AndroidRuntime: 	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:160)
10-01 12:58:08.291  2112  2112 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
10-01 12:58:08.291  2112  2112 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-01 12:58:08.291  2112  2112 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
10-01 12:58:08.291  2112  2112 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6898)
10-01 12:58:08.291  2112  2112 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-01 12:58:08.291  2112  2112 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
10-01 12:58:08.291  2112  2112 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
10-01 12:58:08.291  2112  2112 E AndroidRuntime: Caused by: android.os.TransactionTooLargeException: data parcel size 2618084 bytes
10-01 12:58:08.291  2112  2112 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
10-01 12:58:08.291  2112  2112 E AndroidRuntime: 	at android.os.BinderProxy.transact(Binder.java:1179)
10-01 12:58:08.291  2112  2112 E AndroidRuntime: 	at android.app.IActivityManager$Stub$Proxy.activityStopped(IActivityManager.java:3969)
10-01 12:58:08.291  2112  2112 E AndroidRuntime: 	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:144)
10-01 12:58:08.291  2112  2112 E AndroidRuntime: 	... 7 more
```

**Comment by patzly** [comment] 2020-10-02 17:33
Seems that you have to many products...
`TransactionTooLargeException` is thrown when the bundle of products for a transaction with the next screen is too big.
We don't know how to fix that yet, sorry.

**Comment by ivanboytsov** [comment] 2020-10-02 17:49
I just deleted descriptions. It's all fine now.

**Comment by ivanboytsov** [comment] 2020-10-02 17:50
How many products positions can grocy endure?

**Comment by MrJohnZoidberg** [comment] 2020-10-09 22:32
There is not a too large number of products, the problem is a size limit (I don't know how many bytes) for the storage between two screens – we need to reduce this size through using product names instead of storing all product objects, for example.

I will close this issue and track this in #129.

**Closed by MrJohnZoidberg** 2020-10-09 22:32 UTC
Labels: bug
