### ISSUE TITLE
[v2.0.0] alpha crash when selecting item to consume

### ISSUE THREAD

**Issue by samnewman86** [patzly/grocy-android#330] opened 2021-02-08 20:42 UTC
When selecting an item, or scanning one to consume it the app crashes.

```
--------- beginning of main
02-08 20:38:52.219  8458  8458 E r.patrick.groc: No package ID ff found for ID 0xffffffff.
02-08 20:39:01.885  8458  8458 E r.patrick.groc: No package ID ff found for ID 0xffffffff.
02-08 20:39:03.385  8458  8458 E r.patrick.groc: No package ID ff found for ID 0xffffffff.
02-08 20:39:06.803  8458  8458 E r.patrick.groc: No package ID ff found for ID 0xffffffff.
02-08 20:39:10.105  8458  8458 E r.patrick.groc: No package ID ff found for ID 0xffffffff.
02-08 20:39:52.360  8458  8458 E r.patrick.groc: No package ID ff found for ID 0xffffffff.
--------- beginning of crash
02-08 20:39:57.593  8458  8458 E AndroidRuntime: FATAL EXCEPTION: main
02-08 20:39:57.593  8458  8458 E AndroidRuntime: Process: xyz.zedler.patrick.grocy, PID: 8458
02-08 20:39:57.593  8458  8458 E AndroidRuntime: b.b.b.v: java.lang.NumberFormatException: empty String
02-08 20:39:57.593  8458  8458 E AndroidRuntime: 	at b.b.b.z.z.o$D.b(SourceFile:4)
02-08 20:39:57.593  8458  8458 E AndroidRuntime: 	at b.b.b.z.z.i.a(SourceFile:1)
02-08 20:39:57.593  8458  8458 E AndroidRuntime: 	at b.b.b.z.z.j$a.b(SourceFile:9)
02-08 20:39:57.593  8458  8458 E AndroidRuntime: 	at b.b.b.z.z.n.b(SourceFile:1)
02-08 20:39:57.593  8458  8458 E AndroidRuntime: 	at b.b.b.z.z.b$a.b(SourceFile:6)
02-08 20:39:57.593  8458  8458 E AndroidRuntime: 	at b.b.b.i.b(SourceFile:9)
02-08 20:39:57.593  8458  8458 E AndroidRuntime: 	at b.a.a.a.a.g(Unknown Source:5)
02-08 20:39:57.593  8458  8458 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.h.k.a(SourceFile:3)
02-08 20:39:57.593  8458  8458 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.h.a.a(Unknown Source:4)
02-08 20:39:57.593  8458  8458 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.m.e.a(SourceFile:3)
02-08 20:39:57.593  8458  8458 E AndroidRuntime: 	at b.a.b.w.k.e(SourceFile:5)
02-08 20:39:57.593  8458  8458 E AndroidRuntime: 	at b.a.b.g$b.run(SourceFile:5)
02-08 20:39:57.593  8458  8458 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
02-08 20:39:57.593  8458  8458 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
02-08 20:39:57.593  8458  8458 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
02-08 20:39:57.593  8458  8458 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7711)
02-08 20:39:57.593  8458  8458 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-08 20:39:57.593  8458  8458 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
02-08 20:39:57.593  8458  8458 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
02-08 20:39:57.593  8458  8458 E AndroidRuntime: Caused by: java.lang.NumberFormatException: empty String
02-08 20:39:57.593  8458  8458 E AndroidRuntime: 	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842)
02-08 20:39:57.593  8458  8458 E AndroidRuntime: 	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
02-08 20:39:57.593  8458  8458 E AndroidRuntime: 	at java.lang.Double.parseDouble(Double.java:538)
02-08 20:39:57.593  8458  8458 E AndroidRuntime: 	at b.b.b.B.a.G(SourceFile:16)
02-08 20:39:57.593  8458  8458 E AndroidRuntime: 	at b.b.b.z.z.o$D.b(SourceFile:3)
02-08 20:39:57.593  8458  8458 E AndroidRuntime: 	... 18 more
02-08 20:40:00.342  8459  8459 E r.patrick.groc: Unknown bits set in runtime_flags: 0x20000
02-08 20:40:00.352  8459  8459 E r.patrick.groc: Not starting debugger since process cannot load the jdwp agent.
02-08 20:40:01.544  8459  8459 E r.patrick.groc: No package ID ff found for ID 0xffffffff.
02-08 20:40:03.975  8459  8459 E r.patrick.groc: No package ID ff found for ID 0xffffffff.
02-08 20:40:05.019  8459  8459 E r.patrick.groc: No package ID ff found for ID 0xffffffff.
--------- beginning of system
02-08 20:40:33.583  8459  8459 E r.patrick.groc: No package ID ff found for ID 0xffffffff.
02-08 20:40:50.098  8459  8459 E r.patrick.groc: No package ID ff found for ID 0xffffffff.
02-08 20:40:54.342  8459  8459 E AndroidRuntime: FATAL EXCEPTION: main
02-08 20:40:54.342  8459  8459 E AndroidRuntime: Process: xyz.zedler.patrick.grocy, PID: 8459
02-08 20:40:54.342  8459  8459 E AndroidRuntime: b.b.b.v: java.lang.NumberFormatException: empty String
02-08 20:40:54.342  8459  8459 E AndroidRuntime: 	at b.b.b.z.z.o$D.b(SourceFile:4)
02-08 20:40:54.342  8459  8459 E AndroidRuntime: 	at b.b.b.z.z.i.a(SourceFile:1)
02-08 20:40:54.342  8459  8459 E AndroidRuntime: 	at b.b.b.z.z.j$a.b(SourceFile:9)
02-08 20:40:54.342  8459  8459 E AndroidRuntime: 	at b.b.b.z.z.n.b(SourceFile:1)
02-08 20:40:54.342  8459  8459 E AndroidRuntime: 	at b.b.b.z.z.b$a.b(SourceFile:6)
02-08 20:40:54.342  8459  8459 E AndroidRuntime: 	at b.b.b.i.b(SourceFile:9)
02-08 20:40:54.342  8459  8459 E AndroidRuntime: 	at b.a.a.a.a.g(Unknown Source:5)
02-08 20:40:54.342  8459  8459 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.h.k.a(SourceFile:3)
02-08 20:40:54.342  8459  8459 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.h.a.a(Unknown Source:4)
02-08 20:40:54.342  8459  8459 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.m.e.a(SourceFile:3)
02-08 20:40:54.342  8459  8459 E AndroidRuntime: 	at b.a.b.w.k.e(SourceFile:5)
02-08 20:40:54.342  8459  8459 E AndroidRuntime: 	at b.a.b.g$b.run(SourceFile:5)
02-08 20:40:54.342  8459  8459 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
02-08 20:40:54.342  8459  8459 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
02-08 20:40:54.342  8459  8459 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
02-08 20:40:54.342  8459  8459 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7711)
02-08 20:40:54.342  8459  8459 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-08 20:40:54.342  8459  8459 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
02-08 20:40:54.342  8459  8459 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
02-08 20:40:54.342  8459  8459 E AndroidRuntime: Caused by: java.lang.NumberFormatException: empty String
02-08 20:40:54.342  8459  8459 E AndroidRuntime: 	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842)
02-08 20:40:54.342  8459  8459 E AndroidRuntime: 	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
02-08 20:40:54.342  8459  8459 E AndroidRuntime: 	at java.lang.Double.parseDouble(Double.java:538)
02-08 20:40:54.342  8459  8459 E AndroidRuntime: 	at b.b.b.B.a.G(SourceFile:16)
02-08 20:40:54.342  8459  8459 E AndroidRuntime: 	at b.b.b.z.z.o$D.b(SourceFile:3)
02-08 20:40:54.342  8459  8459 E AndroidRuntime: 	... 18 more
02-08 20:40:58.063  8462  8462 E r.patrick.groc: Unknown bits set in runtime_flags: 0x20000
02-08 20:40:58.072  8462  8462 E r.patrick.groc: Not starting debugger since process cannot load the jdwp agent.
02-08 20:40:59.684  8462  8462 E r.patrick.groc: No package ID ff found for ID 0xffffffff.
02-08 20:41:04.759  8462  8462 E r.patrick.groc: No package ID ff found for ID 0xffffffff.
02-08 20:41:06.884  8462  8462 E r.patrick.groc: No package ID ff found for ID 0xffffffff.
02-08 20:41:07.963  8462  8462 E r.patrick.groc: No package ID ff found for ID 0xffffffff.
02-08 20:42:04.488  8462  8462 E r.patrick.groc: No package ID ff found for ID 0xffffffff.
02-08 20:42:12.965  8462  8462 E r.patrick.groc: No package ID ff found for ID 0xffffffff.
```

**Comment by samnewman86** [comment] 2021-02-08 20:46
I've pasted the log. Let me know if you need anything else

**Comment by MrJohnZoidberg** [comment] 2021-02-08 20:49
Please don't post any comments in the Testing issue xD Every time someone post a comment, all 80 people who subscribed receive an email... Just a reminder, it's not against you. :)

**Comment by MrJohnZoidberg** [comment] 2021-02-08 20:51
The error in the log is hard to find in the code... I will come back to you if I'm working on this, I think this has something to do with your server database, because scanning is working with the demo server.

**Comment by samnewman86** [comment] 2021-02-08 21:04
It's a new install.

**Comment by MrJohnZoidberg** [comment] 2021-02-08 21:06
Mmh can you try if the crash also occurs when you use the demo server in the app, please?

**Comment by samnewman86** [comment] 2021-02-08 21:37
Nope works ok using the demo server. Not sure what could be different

**Comment by MrJohnZoidberg** [comment] 2021-02-08 21:40
Thanks great, I will test it also with a new server the next days, I hope I can reproduce it then.

**Comment by samnewman86** [comment] 2021-02-08 21:51
I just reinstalled the server and tried to add a location using he app. It doesn't seem to save the data to the server

**Comment by samnewman86** [comment] 2021-02-08 22:12
If it helps the server.im.usinf is the home assistant addon

**Comment by samnewman86** [comment] 2021-02-09 14:33
After almost giving up hope, I tried one last time today and everything seems to be working fine. No crashes. I'll keep using and see if it happens again

**Comment by MrJohnZoidberg** [comment] 2021-02-09 14:54
Mmh that's weird, like I already said, I will test the version with my server the next days and maybe I can reproduce the bug then.

**Comment by MrJohnZoidberg** [comment] 2021-02-20 22:38
I hope that I've fixed this crash with the latest version, so I will close this issue. Feel free to open a new one or write here if it still occurs.

**Closed by MrJohnZoidberg** 2021-02-20 22:38 UTC
Labels: bug
