### ISSUE TITLE
Crashing after every product during inventory

### ISSUE THREAD

**Issue by cwrau** [patzly/grocy-android#730] opened 2023-06-24 07:43 UTC
When taking inventory, after scanning the barcode, filling in the necessary info and then after saving that the app crashes with the following log;

```log
--------- beginning of crash
06-24 09:38:46.417 21646 21646 E AndroidRuntime: FATAL EXCEPTION: main
06-24 09:38:46.417 21646 21646 E AndroidRuntime: Process: xyz.zedler.patrick.grocy, PID: 21646
06-24 09:38:46.417 21646 21646 E AndroidRuntime: java.lang.IllegalArgumentException: The detector does not exist
06-24 09:38:46.417 21646 21646 E AndroidRuntime: 	at com.google.android.gms.common.internal.Preconditions.checkArgument(com.google.android.gms:play-services-basement@@18.1.0:6)
06-24 09:38:46.417 21646 21646 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.scanner.EmbeddedFragmentScannerMLKit$$ExternalSyntheticLambda0.accept(R8$$SyntheticClass:31)
06-24 09:38:46.417 21646 21646 E AndroidRuntime: 	at androidx.camera.mlkit.vision.MlKitAnalyzer$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:26)
06-24 09:38:46.417 21646 21646 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
06-24 09:38:46.417 21646 21646 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-24 09:38:46.417 21646 21646 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
06-24 09:38:46.417 21646 21646 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
06-24 09:38:46.417 21646 21646 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7918)
06-24 09:38:46.417 21646 21646 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-24 09:38:46.417 21646 21646 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
06-24 09:38:46.417 21646 21646 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
--------- beginning of main
06-24 09:40:42.297 23283 23283 E r.patrick.grocy: Not starting debugger since process cannot load the jdwp agent.
```

**Comment by dominiczedler** [comment] 2023-06-27 01:24
Thanks for reporting! This is a duplicate of #690, we will look how the crash occurs (still no idea what the problem is).

**Closed by dominiczedler** 2023-06-27 01:24 UTC
Labels: duplicate

**Comment by dominiczedler** [comment] 2023-06-28 00:43
Sorry, I mean #688.
