### ISSUE TITLE
My Idea

### ISSUE THREAD

**Issue by korzeniewski36** [patzly/grocy-android#599] opened 2022-12-16 04:09 UTC
Hello, I can't ask an idea. Will printer support be added, such as in SUNMI V1, Sunmi V2 and Sunmi V2 PRO terminals? It would make things much easier when it comes to printing, for example, a shopping list or inventory. Regards

**Comment by MrJohnZoidberg** [comment] 2022-12-20 21:26
Duplicate of #570

**Closed by MrJohnZoidberg** 2022-12-20 21:26 UTC
Labels: duplicate
