### ISSUE TITLE
Unit and amount incorrect in the app

### ISSUE THREAD

**Issue by Dehalion** [patzly/grocy-android#622] opened 2023-01-06 09:19 UTC
I have a recipe where the amount of ingredients is correct in grocy itself but displayed wrong in the app.

The app displays "5 TL salt" where grocy has only "1 TL" (ratio _TL_ : _g_ is 1:5 and base unit for salt is _g_).
The same error occurs with _Hefe_, where the app shows "42 Würfel" but grocy has "1 Würfel". And the ratio for _Würfel_ : _g_ is also 1:42.
_Wasser_ and _Zucker_ have the same issues, with _Wasser_ being most obvious that it displays the liter amount but _ml_ unit.

It seems the app shows the amount in the ingredients' base unit, but the unit from the recipe. This can be quite catastrophic with ratios of 1:5 for salt.

<img src="https://user-images.githubusercontent.com/1926628/210968586-6ea7ad7e-0db6-4bd7-8a2d-b5e92a9fcd74.jpg" width="400"/>

<img src="https://user-images.githubusercontent.com/1926628/210969107-707cd85f-126d-4190-80bf-9a73ae8806c9.png" width="400"/>

Grocy version: 3.3.2
Grocy-Android version: 2.3.0

PS: Don't judge me for the recipe itself, its copy&paste and has lots of room for improvement, I know :)

**Comment by dominiczedler** [comment] 2023-01-06 10:40
Hello, thanks for reporting!

This is already fixed and you can test it in the current nightly builds (duplicate of #612).

**Closed** 2023-01-06 10:40 UTC
Labels: duplicate
