### ISSUE TITLE
Feature request, widget

### ISSUE THREAD

**Issue by DellanX** [patzly/grocy-android#559] opened 2022-06-23 19:00 UTC
I have a feature request

It'd be cool if there was a widget for Grocy, with a few quick barcode actions: consume, inventory and purchase.
It could also show the list of items running low, the shopping list, or items about to go bad.

**Comment by MrJohnZoidberg** [comment] 2022-07-10 20:35
Duplicate of #256, I will copy your comment into that issue :)

**Closed** 2022-07-10 20:35 UTC
