### ISSUE TITLE
Missing "add barcode" button 

### ISSUE THREAD

**Issue by mlunax** [patzly/grocy-android#414] opened 2021-05-21 09:16 UTC
![Screenshot_2021-05-21-11-14-25-92_ded3d01f237383c8e0209ace216d3455.jpg](https://user-images.githubusercontent.com/11018865/119113964-ef859f00-ba25-11eb-8c61-e73db0f9ecf4.jpg)

**Comment by MrJohnZoidberg** [comment] 2021-05-21 10:01
Duplicate of #391

**Closed by MrJohnZoidberg** 2021-05-21 10:01 UTC
Labels: duplicate
