### ISSUE TITLE
Feature request - implement notifications.

### ISSUE THREAD

**Issue by igor-cali** [patzly/grocy-android#522] opened 2022-04-16 15:14 UTC
Thanks for this app.
I would like to have notifications for items expired or about to expire (within a given time span).
I am transitioning from an app from GStore to Grocy Android. The app from the GStore has a setting to choose if and when is the day the notifications shall be raised.
Such a feature is a major driver to use this kind of apps.

Thanks!

**Comment by MrJohnZoidberg** [comment] 2022-04-16 15:54
Hi, this is a duplicate of #108. But maybe I can ask you here: Why isn't it sufficient for you to regulary check out the start overview page of our app which tells you whether something is in stock which expires? I don't get it why a notification for all devices in the household should do a better job than looking on an information overview. I ask this myself, because when you consume or purchase something with the app, you always open it and in this time you can see already the info on the start page...

**Comment by igor-cali** [comment] 2022-04-16 15:59
Hi, thanks for your reply.
Well, the main advantage is that automation can push information to the user instead of the user to pull it.
In my personal case, I usually have not enough time to check everything. The app I am transitioning from helps me reducing/nullify the waste of expired food.
By the way, I could support on this when I can find some time.

**Comment by MrJohnZoidberg** [comment] 2022-04-16 16:07
Okay I will close this issue then, and the progress will be in the other issue :-)

The main thing which I'm thinking about is the notification technique we can use here... Because we can't use push notifications like all other apps, instead we need to keep the app running in background somehow and check the stock regularly. The background task is something hard for most manufactors because they kill apps constantly which are not used. So I think we must display a permanent notification for that which keeps the app running. And I can see guys already here, complaining about the battery life.

**Closed by MrJohnZoidberg** 2022-04-16 16:07 UTC
Labels: duplicate

**Comment by igor-cali** [comment] 2022-04-16 16:13
That's right. This is basically the concept for a budget app I created myself. In Grocy android there could be an opt-in user setting.
