### ISSUE TITLE
F-droid builds stuck at 2.2.1

### ISSUE THREAD

**Issue by c33s** [patzly/grocy-android#595] opened 2022-11-30 15:14 UTC
just noticed that the builds on fdroid are stuck at 2.2.1 as the android app shows a warning.

i know that fdroid builds can take some time but i assume that it should have been build already by now.

**Comment by patzly** [comment] 2022-11-30 16:23
Duplicate of #591 and #566. Please look in the closed issues before opening a new one :)

**Comment by c33s** [comment] 2022-12-01 11:51
looks like the search is not that good on the gitlab android app i use. i searched for f-droid and i don't found the issues mentioned by you.

**Comment by patzly** [comment] 2022-12-03 00:13
Yeah we will leave this issue open until we release the next version :)
As I described in the other issue, I (and my brother too) currently have to focus on study, so I still need some time to redesign all components (see #588 for progress).

**Comment by lefterisgar** [comment] 2023-01-08 15:55
I think it has now been fixed as version 3.0.0 is available on F-Droid.

**Comment by dominiczedler** [comment] 2023-01-08 19:10
Thanks for the hint, this version release was not intended by us - I think F-Droid did something wrong and didn't wait for a new tag for a release.

**Closed by dominiczedler** 2023-01-08 19:10 UTC
Labels: duplicate

**Comment by matttbe** [comment] 2023-01-16 17:09
> I think F-Droid did something wrong and didn't wait for a new tag for a release. So maybe the real v3.0.0 release won't be built by F-Droid and only the releases after this one.

FYI, I opened a new issue on F-Droid side: https://gitlab.com/fdroid/fdroiddata/-/issues/2873

I don't know what will happen with the next v3.0.0 version and if we can force an update. If not, do you think a v3.0.1 could be created?

(BTW, thank you for developing this nice app!)

**Comment by patzly** [comment] 2023-01-23 17:23
@matttbe Thank you so much! I just finished the big redesign, so the official v3.0.0 should be ready in a few days. I saw that F-Droid removed the wrong version so I hope this is no longer a problem because of your efforts!

**Comment by matttbe** [comment] 2023-01-24 10:22
@patzly my pleasure! Thank you for working on this new version!

From what I understood, it should be OK to have a new `3.0.0` release with the same `versionCode 43`.

If a few hours/days after the release, you don't see the [F-Droid metadata for your app](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/xyz.zedler.patrick.grocy.yml) being updated, feel free to open an issue on their side and/or ping me ;-)
