### ISSUE TITLE
No factor applied when scanning new product

### ISSUE THREAD

**Issue by todu85** [patzly/grocy-android#264] opened 2020-12-20 17:59 UTC
When scanning a new product for shopping and the product is not defined yet, you get a popup to fill in the missing fields. When you now change the units: e.g. 1 package (shop) is 1000g (inventory), just 1g is added to inventory. I guess that the unit conversion is missing, because the fields are saved correctly.

**Comment by radim-ek** [comment] 2020-12-20 21:45
Duplicate of #258

**Comment by MrJohnZoidberg** [comment] 2020-12-20 22:23
Thanks for reporting! But like Radim wrote, this is a duplicate of an already fixed issue. We will release the new version with this fix in a few days.

**Closed** 2021-01-11 20:18 UTC
Labels: duplicate

**Comment by MrJohnZoidberg** [comment] 2021-01-11 20:20
Sorry, we won't release another version before `v2.0.0`... I hope this is ok. The upcoming version will contain the fix.
