### ISSUE TITLE
App can show old data if page loading was interrupted

### ISSUE THREAD

**Issue by Saturo78** [patzly/grocy-android#409] opened 2021-05-17 20:29 UTC
I have 0.5 pack of a product on stock.
Stockoverview shows 1 Pack. When i click on the position the opening window shows 0.5 pack.

**Comment by MrJohnZoidberg** [comment] 2021-05-17 22:44
Mmh I cannot reproduce that :|

**Comment by MrJohnZoidberg** [comment] 2021-05-17 23:23
Have you swiped down to refresh data on the stock overview page?

**Comment by Saturo78** [comment] 2021-05-18 05:44
No, i did not refresh. Because the productoverview shows the right amount, i did not thought it was neccesary.

**Comment by MrJohnZoidberg** [comment] 2021-05-18 06:09
Ok, and after a refresh it is/was the right amount in the list?
Please understand that I cannot fix anything which I cannot reproduce. So a little more information without asking everytime would be great.

**Comment by Saturo78** [comment] 2021-05-18 17:05
Yes, thats correct.
When you consume something and switch to the stockoverview after that, it shows the old amount untill you swipe down to refresh. But when you click on the entry to bring up the productoverview the right amount is shown.

**Comment by MrJohnZoidberg** [comment] 2021-05-18 21:40
Sorry, I still cannot reproduce it (after consume the correct amount is shown in stock overview):

https://user-images.githubusercontent.com/27244574/118726860-314df400-b832-11eb-8711-5d30d55cc1a8.mp4

Does this issue only occur with one special product or with all products in your stock?

**Comment by Saturo78** [comment] 2021-05-18 22:42
I have tried again with the same result.

https://user-images.githubusercontent.com/71584438/118732646-0caa4a00-b83b-11eb-8b57-410739340e13.mp4

**Comment by MrJohnZoidberg** [comment] 2021-05-19 15:51
Thanks for your demo. I will let this open, but sorry I still can't reproduce it and thus cannot provide a fix for it...

**Comment by MrJohnZoidberg** [comment] 2021-05-24 00:09
I think I now know what the bug is. Please check again if the issue also occurs when you do exactly the same navigation steps like in your screenrecord above but now please wait on the start overview page (NOT the stock overview page) until the loading circle disappears. Does the issue still occur then? Thanks for your help!

**Comment by MrJohnZoidberg** [comment] 2021-05-31 14:57
@Saturo78 ? Please reply to my last comment here.

**Comment by Saturo78** [comment] 2021-05-31 19:32
I could not reproduce the behaviour when i wait until the loading circle disappears.

**Comment by MrJohnZoidberg** [comment] 2021-08-30 17:51
Short update here: I know where the bug is, but it takes time to change the whole implementation how loading with queues works in our app. So please be patient, it will be fixed after v2.0.0 release.

You already know the workaround: wait until the loading circle disappears.

**Closed** 2022-03-13 03:32 UTC
Labels: bug
