### ISSUE TITLE
Feature support : Meal planning

### ISSUE THREAD

**Issue by YasTouchedMySpaggett** [patzly/grocy-android#574] opened 2022-09-24 03:44 UTC
I recently started using the meal planning feature on the web interface, works well if you try to budget and/or doing a diet. The thing is the not so techies like my partner only uses the app. Would it be possible to add that to the app too? If yes and it requires developing i could help.

**Comment by MrJohnZoidberg** [comment] 2022-09-24 11:06
Duplicate of #524.

**Closed by MrJohnZoidberg** 2022-09-24 11:06 UTC

**Comment by MrJohnZoidberg** [comment] 2022-09-24 11:09
I will work on the feature after we've finished the redesign. :-)

**Comment by YasTouchedMySpaggett** [comment] 2022-09-27 12:20
Thank you for your reply, i didnt find that issue before so thank you for tagging it. Appreciate the efforts of the whole team : )))
