### ISSUE TITLE
Add option in settings for timeout duration

### ISSUE THREAD

**Issue by basxto** [patzly/grocy-android#151] opened 2020-10-17 21:13 UTC
Scanning barcodes works and I sometimes can connect them with products.
But not always, since the list shown is pretty encomplety.

Locations, stores, quantity units and product groups says offline.
Stock and everything else in master data never shows something other than `Uups! An error occured`.
Shopping list always claims to be emtpy and offline

I’m having trouble getting anything meaningful from the logs. Once I saw a 400, but not on the nginx side. Mostly it just has some kind of crash logs.

The app runs on Fairphone with ArrowOS based on Android 9.
Grocy runs on raspi1 and I suspect that’s the main problem, since it’s quite slow.
Grocy runs with nginx+php-fpm, before I used `php -S`, I switched because I suspected it could be a problem, that can just answer just one request at a time, but I think it became slower.
I do https via apache2 running on my other pi (necessary for barcode scanning in my browser) with certificates from letsencrypt.
It neither worked before I had apache2 inbetween and it definitely connected, grocy registered api key as being used.
I see the requests in nginx access logs, it responds 200 and when I open the requested URLs in my browser they look fine.

I’m currently playing around with python bindings and I have no trouble connecting there, so the API itself should work.

**Comment by MrJohnZoidberg** [comment] 2020-10-17 21:47
Mmh, I don't know how I can help you with that. We just use the Volley Request library in our app, and we never received such an issue before... So like you said the problem is maybe the slow Raspi1 which needs time to handle a request.
If this duration is over 5 seconds, Volley will give a timeout error and this could result in `Uups! An error occured` (better error descriptions will come with `v2.0.0`).

So: do you sometimes wait equal or longer than 5 seconds on your grocy webserver interface for a request to be completed?
If yes, then your slow Raspi AND the default timeout of 5 secs in Volley are the source of the problem and we could provide an option for custom timeout duration in `v2.0.0`.

**Comment by basxto** [comment] 2020-10-17 21:53
Opening stock in my web browser takes about 10 seconds.

And I copied an info log crash:
```
--------- beginning of crash
10-12 17:17:58.871  7007  7007 E AndroidRuntime: FATAL EXCEPTION: main
10-12 17:17:58.871  7007  7007 E AndroidRuntime: Process: xyz.zedler.patrick.grocy, PID: 7007
10-12 17:17:58.871  7007  7007 E AndroidRuntime: java.lang.IllegalStateException: FragmentManager has been destroyed
10-12 17:17:58.871  7007  7007 E AndroidRuntime: 	at androidx.fragment.app.o.J(SourceFile:3)
10-12 17:17:58.871  7007  7007 E AndroidRuntime: 	at androidx.fragment.app.a.q(SourceFile:12)
10-12 17:17:58.871  7007  7007 E AndroidRuntime: 	at androidx.fragment.app.a.f(SourceFile:1)
10-12 17:17:58.871  7007  7007 E AndroidRuntime: 	at androidx.fragment.app.b.X0(SourceFile:5)
10-12 17:17:58.871  7007  7007 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.activity.SettingsActivity.B0(SourceFile:2)
10-12 17:17:58.871  7007  7007 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.activity.SettingsActivity.Y(SourceFile:1)
10-12 17:17:58.871  7007  7007 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.activity.b1.run(Unknown Source:2)
10-12 17:17:58.871  7007  7007 E AndroidRuntime: 	at c.a.a.a.k.t.a(SourceFile:1)
10-12 17:17:58.871  7007  7007 E AndroidRuntime: 	at c.a.a.a.k.f.a(Unknown Source:2)
10-12 17:17:58.871  7007  7007 E AndroidRuntime: 	at c.a.a.a.i.T$u.c(SourceFile:2)
10-12 17:17:58.871  7007  7007 E AndroidRuntime: 	at c.a.a.a.i.C.a(Unknown Source:2)
10-12 17:17:58.871  7007  7007 E AndroidRuntime: 	at c.a.a.a.i.V.b(SourceFile:5)
10-12 17:17:58.871  7007  7007 E AndroidRuntime: 	at c.a.a.a.i.j.a(Unknown Source:8)
10-12 17:17:58.871  7007  7007 E AndroidRuntime: 	at c.a.a.a.i.M.a(Unknown Source:4)
10-12 17:17:58.871  7007  7007 E AndroidRuntime: 	at b.a.b.w.k.e(SourceFile:5)
10-12 17:17:58.871  7007  7007 E AndroidRuntime: 	at b.a.b.g$b.run(SourceFile:5)
10-12 17:17:58.871  7007  7007 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
10-12 17:17:58.871  7007  7007 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-12 17:17:58.871  7007  7007 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
10-12 17:17:58.871  7007  7007 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6739)
10-12 17:17:58.871  7007  7007 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-12 17:17:58.871  7007  7007 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
10-12 17:17:58.871  7007  7007 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:859)
--------- beginning of system
--------- beginning of main
10-17 22:52:44.183  3778  3778 W InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.
10-17 23:44:46.777  3778  3778 W InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.  
```

But I remember I also read Volley in other logs.

**Comment by MrJohnZoidberg** [comment] 2020-10-17 22:14
Ok, maybe you can buy a Raspi 3? :-) That would be more comfortable for you (not slow anymore) and we wouldn't need to add a new option for timeout.

I say this because `v2.0.0` will not come before Christmas (because we are busy), so you would have to wait for this timeout option – I'm sorry for that.

**Comment by basxto** [comment] 2020-10-17 22:43
I have a raspi3, but I have to setup a new image for this, alarm does not appear to support multiple raspi versions at the same time.
But I’ll try if the problems are gone then.

Christmas does not seem that far away, though

**Comment by MrJohnZoidberg** [comment] 2020-10-22 17:29
Oh sorry, I didn't see your Edit :-) 

Yes, the plan is to add an option for timeout duration. With #177 merged, v1.9.0 has to work for you now (I think 30secs are long enough).

**Comment by basxto** [comment] 2020-10-28 01:28
Sorry, I did not notice there was a release.
It appears to work now. I see the stock, I see the shopping list ‼ and it looks like the scanning finds products now.
Thank you a lot 💖

I will do my first grocy shopping later today then.

But there is no option for this, right? The timeout time just increased.

**Comment by MrJohnZoidberg** [comment] 2020-10-28 17:55
Thanks for your feedback, you're welcome!
I will open this issue again because I planned to add an option for timeout duration in app settings, maybe it will come with `v2.0.0` because then you will be able to reach settings from login screen and not only after login.

**Closed** 2021-01-24 20:07 UTC
Labels: enhancement
