### ISSUE TITLE
xx below min. stock amount inconsistency

### ISSUE THREAD

**Issue by szimszon** [patzly/grocy-android#119] opened 2020-09-29 16:44 UTC
Hi,

I wonder if you could help me.

I have lots of products with parent product and "Accumulate sub products min. stock amount" checked in parent product.
In the bubble I see the correct number and in the list I see all the parent product and not only with not enough child product.

Could it be fixed?
Thank you!

**Comment by MrJohnZoidberg** [comment] 2020-10-03 15:36
Thank you for reporting that issue! I will look into it as soon as I have enough time.

**Comment by ivanboytsov** [comment] 2020-10-05 06:58
I have the same issue. All parent products are included. So it is almost impossible to find out what products are missing.

**Comment by MrJohnZoidberg** [comment] 2020-10-10 20:23
> in the list I see all the parent product and not only with not enough child product.

Hi, can you please explain this a bit more? I cannot reproduce this, maybe you can say an example with amounts so that I can understand it better.

**Comment by ivanboytsov** [comment] 2020-10-11 06:55
My below min stock (6) in web app
![Screenshot_20201011-095148_Chrome](https://user-images.githubusercontent.com/70232503/95672205-87293200-0ba7-11eb-855c-be36054c44bd.jpg)
And in android app
![Screenshot_20201011-095209_Grocy](https://user-images.githubusercontent.com/70232503/95672213-97411180-0ba7-11eb-9bc8-8a5e96014203.jpg)
As you see in the last screenshot it is not 6, as shown in filter. That's because filter doesn't exclude parent products, which has enough child products for minimal amount fulfillment.

**Comment by ivanboytsov** [comment] 2020-10-11 07:03
So below min stock amount filter has to exclude products with checked "Accumulate sub products min. stock amount" where accumulated amount of child (sub) products greater than specified minimal stock amount.

**Comment by MrJohnZoidberg** [comment] 2020-10-11 11:07
Ah, thanks now I can reproduce it.

**Comment by MrJohnZoidberg** [comment] 2020-10-23 17:52
Fixed in f2069eb

**Closed by MrJohnZoidberg** 2020-10-23 17:52 UTC
Labels: bug

**Comment by MrJohnZoidberg** [comment] 2020-10-23 17:53
Please test the issue again with v1.9.0 as soon as it is available and report any further inconsistencies please.

**Comment by ivanboytsov** [comment] 2020-10-28 07:37
> Any feedback if it's fixed?

It is okay now. Thanks.
