### ISSUE TITLE
Crash when clicking on Preparation of a recipe

### ISSUE THREAD

**Issue by Amasis** [patzly/grocy-android#581] opened 2022-09-30 17:29 UTC
I have a crash when clicking on preparation. 
If you need further information, I'll be glad to provide more :-)

**Steps to reproduce**
- Open a recipe
- click on edit symbol  to be in Edit recipe mode
- click Preparation
->  Grocy app crashes

Grocy: 2.3.0

```
--------- beginning of crash
09-30 19:04:16.983 30893 30893 E AndroidRuntime: FATAL EXCEPTION: main
09-30 19:04:16.983 30893 30893 E AndroidRuntime: Process: xyz.zedler.patrick.grocy, PID: 30893
09-30 19:04:16.983 30893 30893 E AndroidRuntime: java.lang.IllegalAccessError: Field 'org.ccil.cowan.tagsoup.ElementType.theAtts' is inaccessible to class 'org.wordpress.aztec.AztecHtmlSchema' (declaration of 'org.wordpress.aztec.AztecHtmlSchema' appears in base.apk)
09-30 19:04:16.983 30893 30893 E AndroidRuntime: 	at org.wordpress.aztec.AztecHtmlSchema.<init>(AztecHtmlSchema.kt:3)
09-30 19:04:16.983 30893 30893 E AndroidRuntime: 	at org.wordpress.aztec.Html$HtmlParser.<clinit>(Unknown Source:2)
09-30 19:04:16.983 30893 30893 E AndroidRuntime: 	at org.wordpress.aztec.AztecParser.fromHtml(AztecParser.kt:5)
09-30 19:04:16.983 30893 30893 E AndroidRuntime: 	at org.wordpress.aztec.AztecText.fromHtml(AztecText.kt:5)
09-30 19:04:16.983 30893 30893 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.fragment.EditorHtmlFragment.onViewCreated(EditorHtmlFragment.java:18)
09-30 19:04:16.983 30893 30893 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:45)
09-30 19:04:16.983 30893 30893 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:28)
09-30 19:04:16.983 30893 30893 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:138)
09-30 19:04:16.983 30893 30893 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:10)
09-30 19:04:16.983 30893 30893 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:14)
09-30 19:04:16.983 30893 30893 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager$5.run(Unknown Source:3)
09-30 19:04:16.983 30893 30893 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
09-30 19:04:16.983 30893 30893 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-30 19:04:16.983 30893 30893 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:233)
09-30 19:04:16.983 30893 30893 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:344)
09-30 19:04:16.983 30893 30893 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8212)
09-30 19:04:16.983 30893 30893 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-30 19:04:16.983 30893 30893 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
09-30 19:04:16.983 30893 30893 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
--------- beginning of system
09-30 19:04:23.970  2195  2195 E OplusCustomizeRestrictionManager: sInstance is null, start a new sInstance
09-30 19:04:34.296  2195  2195 E AndroidRuntime: FATAL EXCEPTION: main
09-30 19:04:34.296  2195  2195 E AndroidRuntime: Process: xyz.zedler.patrick.grocy, PID: 2195
09-30 19:04:34.296  2195  2195 E AndroidRuntime: java.lang.IllegalAccessError: Field 'org.ccil.cowan.tagsoup.ElementType.theAtts' is inaccessible to class 'org.wordpress.aztec.AztecHtmlSchema' (declaration of 'org.wordpress.aztec.AztecHtmlSchema' appears in base.apk)
09-30 19:04:34.296  2195  2195 E AndroidRuntime: 	at org.wordpress.aztec.AztecHtmlSchema.<init>(AztecHtmlSchema.kt:3)
09-30 19:04:34.296  2195  2195 E AndroidRuntime: 	at org.wordpress.aztec.Html$HtmlParser.<clinit>(Unknown Source:2)
09-30 19:04:34.296  2195  2195 E AndroidRuntime: 	at org.wordpress.aztec.AztecParser.fromHtml(AztecParser.kt:5)
09-30 19:04:34.296  2195  2195 E AndroidRuntime: 	at org.wordpress.aztec.AztecText.fromHtml(AztecText.kt:5)
09-30 19:04:34.296  2195  2195 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.fragment.EditorHtmlFragment.onViewCreated(EditorHtmlFragment.java:18)
09-30 19:04:34.296  2195  2195 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:45)
09-30 19:04:34.296  2195  2195 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:28)
09-30 19:04:34.296  2195  2195 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:138)
09-30 19:04:34.296  2195  2195 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:10)
09-30 19:04:34.296  2195  2195 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:14)
09-30 19:04:34.296  2195  2195 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager$5.run(Unknown Source:3)
09-30 19:04:34.296  2195  2195 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
09-30 19:04:34.296  2195  2195 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-30 19:04:34.296  2195  2195 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:233)
09-30 19:04:34.296  2195  2195 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:344)
09-30 19:04:34.296  2195  2195 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8212)
09-30 19:04:34.296  2195  2195 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-30 19:04:34.296  2195  2195 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
09-30 19:04:34.296  2195  2195 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
09-30 19:04:45.351  2561  2561 E OplusCustomizeRestrictionManager: sInstance is null, start a new sInstance
09-30 19:05:14.952  2561  2561 E AndroidRuntime: FATAL EXCEPTION: main
09-30 19:05:14.952  2561  2561 E AndroidRuntime: Process: xyz.zedler.patrick.grocy, PID: 2561
09-30 19:05:14.952  2561  2561 E AndroidRuntime: java.lang.IllegalAccessError: Field 'org.ccil.cowan.tagsoup.ElementType.theAtts' is inaccessible to class 'org.wordpress.aztec.AztecHtmlSchema' (declaration of 'org.wordpress.aztec.AztecHtmlSchema' appears in base.apk)
09-30 19:05:14.952  2561  2561 E AndroidRuntime: 	at org.wordpress.aztec.AztecHtmlSchema.<init>(AztecHtmlSchema.kt:3)
09-30 19:05:14.952  2561  2561 E AndroidRuntime: 	at org.wordpress.aztec.Html$HtmlParser.<clinit>(Unknown Source:2)
09-30 19:05:14.952  2561  2561 E AndroidRuntime: 	at org.wordpress.aztec.AztecParser.fromHtml(AztecParser.kt:5)
09-30 19:05:14.952  2561  2561 E AndroidRuntime: 	at org.wordpress.aztec.AztecText.fromHtml(AztecText.kt:5)
09-30 19:05:14.952  2561  2561 E AndroidRuntime: 	at xyz.zedler.patrick.grocy.fragment.EditorHtmlFragment.onViewCreated(EditorHtmlFragment.java:18)
09-30 19:05:14.952  2561  2561 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:45)
09-30 19:05:14.952  2561  2561 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:28)
09-30 19:05:14.952  2561  2561 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:138)
09-30 19:05:14.952  2561  2561 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:10)
09-30 19:05:14.952  2561  2561 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:14)
09-30 19:05:14.952  2561  2561 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager$5.run(Unknown Source:3)
09-30 19:05:14.952  2561  2561 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
09-30 19:05:14.952  2561  2561 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-30 19:05:14.952  2561  2561 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:233)
09-30 19:05:14.952  2561  2561 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:344)
09-30 19:05:14.952  2561  2561 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8212)
09-30 19:05:14.952  2561  2561 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-30 19:05:14.952  2561  2561 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
09-30 19:05:14.952  2561  2561 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
09-30 19:05:19.661  2947  2947 E OplusCustomizeRestrictionManager: sInstance is null, start a new sInstance
```

**Comment by MrJohnZoidberg** [comment] 2022-10-05 01:25
Thanks for your report! The issue is already fixed in the next version, because we've implemented a new editor library which works like the editor on the grocy webserver.

**Closed by MrJohnZoidberg** 2022-10-05 01:25 UTC
