### ISSUE TITLE
Instead of purchase unit, stock unit is used

### ISSUE THREAD

**Issue by loziniak** [patzly/grocy-android#259] opened 2020-12-09 22:56 UTC
When I enter **scanning** mode from main (stock) screen, then select **purchase**, and then add **new** product, Then it is added to the stock with **stock units**, instead of purchase units.

**Comment by radim-ek** [comment] 2020-12-09 23:33
Duplicate of 258#

**Comment by MrJohnZoidberg** [comment] 2020-12-12 16:12
Thanks @radim-ek, yes this will be fixed in the next version `v1.10.2`.

**Closed** 2020-12-12 16:13 UTC
Labels: duplicate
