### ISSUE TITLE
Mismatch in ingredient overview and recipe overview.

### ISSUE THREAD

**Issue by Quantum1337** [patzly/grocy-android#626] opened 2023-01-07 10:01 UTC
I have a mismatch in amount of an ingredient in those two views: (See ingredient Olivenöl. All others are correct.)

![Screenshot_20230107-105807_Grocy.png](https://user-images.githubusercontent.com/36477626/211144782-a776bbab-9185-45c2-8160-f739e4de717a.png)

![Screenshot_20230107-105746_Grocy.png](https://user-images.githubusercontent.com/36477626/211144787-9f66dea6-4354-4805-9b59-402ef191efcb.png)

**Comment by dominiczedler** [comment] 2023-01-08 19:18
I think this was already fixed in the latest nightly builds (available under Github releases). So please test it again with that version and reopen the issue if it still exists.

Duplicate of #612

**Comment by Quantum1337** [comment] 2023-01-09 16:24
I tested it with the latest nighly build (master-20230901) and its still there. Please reopen

**Closed** 2023-06-19 00:36 UTC
Labels: bug, duplicate
