### ISSUE TITLE
[Home Assistant] Offline error

### ISSUE THREAD

**Issue by WHagenauw** [patzly/grocy-android#670] opened 2023-03-10 14:16 UTC
Just this morning the grocy app is offline. As well in the 3.0 version and 3.1 version. I did not make any changes since yesterday. I use HA add on as server and there grocy  is online. Anyone else has this problem? What can be the cause?

**Comment by bbalazs** [comment] 2023-03-10 16:28
Grocy on Android (3.0) stopped working and when I try to reconfigure it on the phone it wont accept the API key. Access via HA works without problems.

**Comment by dominiczedler** [comment] 2023-03-10 17:03
We don't know what the source of the problem is - and if version 3.0 randomly stopped working and was working before, we have nothing to do with it...

Is something in the logs after you enabled debugging logs?

**Comment by bbalazs** [comment] 2023-03-10 17:27
This is the log. Doesnt help much I guess...

03-10 18:04:20.958  8083 11655 E Volley  : [144] BasicNetwork.performRequest: Unexpected response code 401 for https://xxx.duckdns.org/api/hassio/ingress/session
03-10 18:04:20.974  8083 11655 E Volley  : [144] BasicNetwork.performRequest: Unexpected response code 401 for https://xxx.duckdns.org/api/hassio/ingress/session
03-10 18:04:20.975  8083  8083 E LoginRequestViewModel: homeAssistantSessionAuth: /api/hassio/ingress/session: error: com.android.volley.AuthFailureError
03-10 18:04:21.003  8083 11657 E Volley  : [146] BasicNetwork.performRequest: Unexpected response code 401 for https://xxx.duckdns.org/api/hassio_ingress/xxx/api/system/info
03-10 18:04:21.023  8083 11657 E Volley  : [146] BasicNetwork.performRequest: Unexpected response code 401 for https://xxx.duckdns.org/api/hassio_ingress/xxx/api/system/info
03-10 18:04:21.024  8083  8083 E LoginRequestViewModel: requestLogin: VolleyError: com.android.volley.AuthFailureError
03-10 18:04:21.050  8083 11656 E Volley  : [145] BasicNetwork.performRequest: Unexpected response code 401 for https://xxx.duckdns.org/api/hassio/ingress/session
03-10 18:04:21.073  8083 11656 E Volley  : [145] BasicNetwork.performRequest: Unexpected response code 401 for https://xxx.duckdns.org/api/hassio/ingress/session
03-10 18:04:21.074  8083  8083 E LoginRequestViewModel: checkHassLongLivedToken (/api/hassio/ingress/session): error: com.android.volley.AuthFailureError

I have tried to c&p and QR code for entering the long-lived token

**Comment by dominiczedler** [comment] 2023-03-10 23:04
Seems like latest Home Assistant Core update breaks functionality of getting a session token with the long-lived access token... Just tested it and the `/api/hassio/ingress/session` worked until I've installed the update. Now there is only error 401 as response but I don't know why. The grocy addon page is still working because there the session token is fetched in another way through websocket which I don't understand.

So I don't know how I can fix this issue, seems that Home Assistant has a bug here.

**Comment by dominiczedler** [comment] 2023-03-11 17:35
Quick update: I think I can fix the issue and you won't need to change anything in the config. I'm on it.

**Comment by dominiczedler** [comment] 2023-03-11 21:19
Hopefully this is fixed now, I've implemented a whole new websocket connection flow and thus this might be a bit buggy for Home Assistant users, especially if you have a slow network connection.

To all: Please test the latest nightly build and give feedback here. For me it works already, but it would be interesting if Nabu Casa (cloud) or duckdns users have issues with the new Home Assistant session handling. Thanks!

**Comment by WHagenauw** [comment] 2023-03-12 08:48
I like to test it. I use Nabu Casa. When will this be released? I just checked in the Play store for updates but it was not there.

**Comment by dominiczedler** [comment] 2023-03-12 09:02
@WHagenauw Please try the nightly build first, which is in the release section here on Github. That's for test purposes before we release a new version in Playstore.

**Comment by WHagenauw** [comment] 2023-03-12 12:47
I just installed the nightly version. Added it to the HA grocy Addon server via a long lived token easily. Had a product on my shopping list waiting to be scanned to add it to the inventory. I could do that and saw that the quantity went up. After that I checked it in the HA Grocy version to see if it communicated with the server and it did. So looks like it is working. Thanks! Now waiting for the official release

**Comment by bbalazs** [comment] 2023-03-12 15:24
I can confirm the nightly to work on self hosted HA with DuckDNS. Thanks for fixing this so quickly!

**Comment by marrobHD** [comment] 2023-03-13 21:47
Sadly I can't confirm that it works for me:
> E Volley  : [1085] BasicNetwork.performRequest: Unexpected response code 401 for https://DOMAIN/api/hassio_ingress/INGRESS/api/system/info

**Comment by WHagenauw** [comment] 2023-03-13 21:56
Strangest thing is that it works today  on my tablet but not on my phone now. I will test it tomorrow on my tablet again.

**Comment by WHagenauw** [comment] 2023-03-14 14:31
My tablet is still ok. They use the same server ofcourse.

**Comment by WHagenauw** [comment] 2023-03-14 17:43
On my phone it is working now. What I did: I logged out in the app, created a nieuw API key in Grocy, than it tells me that I use HA addon as a server and I need to make a long lived token, so I did and scanned the QR code and now it is working. Still strange that my tablet is still working on the old login, even with the latest app version

**Comment by marrobHD** [comment] 2023-03-14 18:08
> On my phone it is working now. What I did: I logged out in the app, created a nieuw API key in Grocy, than it tells me that I use HA addon as a server and I need to make a long lived token, so I did and scanned the QR code and now it is working. Still strange that my tablet is still working on the old login, even with the latest app version 

I also recreated everything. Still won't and didn't work :/

**Comment by r100gs** [comment] 2023-03-15 15:18
I Made new Codes and IT works, but the next day grocy shows as offline

**Comment by nbasse** [comment] 2023-03-15 15:56
With the new fix in 3.1 the app stopped working with above mentioned offline version for me.
I'm still on Home Assistant Core 2022.6.7.
(Note to self: Disable automatic updates on Android apps connecting to home assistant and only update while updating the whole system.)

**Comment by patzly** [comment] 2023-03-15 21:12
@nbasse The problem is not an update of our app, instead auto-updating of Home Assistant is the problem! That's why our app stopped working for you without any action on our side, because your HA updated itself automatically.

**Comment by nbasse** [comment] 2023-03-15 21:34
> @nbasse The problem is not an update of our app, instead auto-updating of Home Assistant is the problem! That's why our app stopped working for you without any action on our side, because your HA updated itself automatically.

No, it was working a few days ago, and it's been longer than that since the pushed auto update for supervisor happened. And you said the update to HA core was the issue. As I wrote I'm still on 2022.6.7

But I'm not here to blame anyone, just to inform that the latest fix broke backward compatability with an earlier version om home assistant.

When I have time I will try to uninstall 3.1 and install 3.0 again to see if it works to be sure of my claims 😉

**Comment by dominiczedler** [comment] 2023-03-15 21:44
@nbasse The missing backwards compatibility can be true, I didn't test it with an older version, sorry. I'm disappointed how the Home Assistant developer said that grocy add-on users should use the "external port" option if they want to have the API accessible because the old way through ingress authentication worked fine. But as it wasn't an official way I can understand the abrupt change and I simply implemented the way how the Home Assistant webpage works with authentication in the latest update. So it can be true that they changed something from the old possible way to the new which breaks compatibility in both directions in our app.

**Comment by marrobHD** [comment] 2023-03-15 21:50
Did you really test grocy against the newest home assistant core + supervisor Version? I use the newest version on both, and on grocy ofc. 
I does not work :/

**Comment by dominiczedler** [comment] 2023-03-15 21:55
@marrobHD Sorry that it doesn't work for you right now, I will have some time on the weekend for development - I can see that the quick fix is not working for everyone, I will have to spend more time on testing and fixing.

I think until another fix the only way is the web interface or the external port option (which I would only recommend when a HTTPS certificate is available but I didn't find a way to generate one in Home Assistant). Sorry for any inconvenience...

**Comment by nbasse** [comment] 2023-03-15 22:14
I have now confirmed that downgrading the grocy app to 3.1.0 makes it work again for me with home assistant  core version 2022.6.7
So I'll just have to use that version until I have time to do a full upgrade of my system.
Thank you for your work with this great app!

**Comment by marrobHD** [comment] 2023-03-15 22:28
> @marrobHD Sorry that it doesn't work for you right now, I will have some time on the weekend for development - I can see that the quick fix is not working for everyone, so I will spend more time on testing and fixing.
> 
> I think until another fix the only way is the web interface or the external port option (which I would only recommend when a HTTPS certificate is available but I didn't find a way to generate one in Home Assistant). Sorry for any inconvenience...

No stress. The grocy app isn't necessary in my workflow, so it's completely fine. However I'd be okay to test some alphas.

**Comment by WHagenauw** [comment] 2023-03-23 12:03
Any news around this issue? I have it working on one tablet but my phone is not working anymore. In April I like to update home Assistant but am hesitating.

**Comment by Auroria-code** [comment] 2023-03-23 23:21
Not sure if this is the same problem, but our phones (bf and i) are also offline with HA. (Maybe @codesalatdev can say something about our HA if needed ^^') it says offline on both phones even with the newest update.

**Comment by dominiczedler** [comment] 2023-03-24 23:41
Hey folks, there was a stupid mistake in the code (hardcoded IP address for test case of my local Home Assistant instance, screenshot below)... Next time I will be more carful with such things. Sorry for not investigating the bug earlier, I hope that the latest nightly works for all users. Please let me know if that's the case or not.

Sorry for any inconveniences...

![image](https://user-images.githubusercontent.com/27244574/227661875-a6a59c35-06a3-410d-80d0-abc2d4a530b1.jpeg)

**Comment by marrobHD** [comment] 2023-03-25 06:31
> Hey folks, there was a stupid mistake in the code (hardcoded IP address for test case of my local Home Assistant instance, screenshot below)... Next time I will be more carful with such things. Sorry for not investigating the bug earlier, I hope that the latest nightly works for all users. Please let me know if that's the case or not.
> 
> Sorry for any inconveniences...
> I don't know why it was working for some users, maybe they have done a fresh log in in the app before usage and then the session token was available (because on login screen there is other code for that without the mistake). 
> 
> ![image](https://user-images.githubusercontent.com/27244574/227661875-a6a59c35-06a3-410d-80d0-abc2d4a530b1.jpeg)
> 

Sadly it doesn't seem to work for me, every time I try to authenticate, I get following message in HA Supervisor logs:
`23-03-25 07:27:10 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session None`

```
In the grocy app, I receive following:
03-25 07:29:42.433 16594 23971 E LoginRequestViewModel: createWebSocketClient: onException: There is no header named Upgrade
03-25 07:29:42.879 16594 23965 E Volley  : [19447] NetworkUtility.shouldRetryException: Unexpected response code 401 for https://myhainstance/api/hassio_ingress/SnGXC6Le1WExFDlp8Zg68oj-mw0B3sZNZGYTy240FVk/api/system/info
03-25 07:29:42.896 16594 23965 E Volley  : [19447] NetworkUtility.shouldRetryException: Unexpected response code 401 for https://myhainstance/api/hassio_ingress/SnGXC6Le1WExFDlp8Zg68oj-mw0B3sZNZGYTy240FVk/api/system/info
03-25 07:29:42.897 16594 16594 E LoginRequestViewModel: requestLogin: VolleyError: com.android.volley.AuthFailureError
```

**Comment by WHagenauw** [comment] 2023-03-26 07:52
Don't have time this weekend to check the nightly build. When will it be released? Since the problem started I had one tablet that was working fine all the time (used it everyday) until this morning...... Now I have there the offline message also while there has been no update from the app or HA. So hopefully the nightly build (if this solves the problem) will be released quickly.

**Comment by patzly** [comment] 2023-03-26 14:31
The nightly build is built automatically every night, you can simply download the current nightly in the release section here on GitHub.

**Comment by codesalatdev** [comment] 2023-03-26 16:42
Going to chime in per request by @Auroria-code :smile: 


Nightly works, but only with local connections (LAN). Using the public URL (that is configured automatically by scanning the QR Code), I get the usual
```
03-26 18:30:30.539 31873 31873 E LoginRequestViewModel: requestLogin: VolleyError: com.android.volley.AuthFailureError
03-26 18:31:07.194 31873 25859 E Volley  : [4439] NetworkUtility.shouldRetryException: Unexpected response code 401 for https://<EXTERNAL_DOMAIN>/api/hassio_ingress/<INGRESS_ID>/api/system/info
```
If I go back in the setup screen and change the external address to the internal one, everything works fine.

**Comment by WHagenauw** [comment] 2023-03-30 08:21
I just tested the nightly build from yesterday in my phone and it works. But even on the official released version I could add the server. On the other hand, this morning I downloaded the nightly build this morning on my tablet and cannot get it working. Not even with the official version

**Comment by codesalatdev** [comment] 2023-03-30 14:19
> I just tested the nightly build from yesterday in my phone and it works. But even on the official released version I could add the server. On the other hand, this morning I downloaded the nightly build this morning on my tablet and cannot get it working. Not even with the official version

Yea, it seems to be inconsistent with the release version. I was 100% sure I got it to work there also, but one day later I got the offline error again, so I modified my comment.

**Comment by dominiczedler** [comment] 2023-04-13 21:57
Sorry, I was busy during the last weeks - I just asked @codesalatdev to support me for debugging the Home Assistant connection, because on my test instance the app works without any offline error...

**Comment by dominiczedler** [comment] 2023-04-14 17:05
@WHagenauw @marrobHD @nbasse @r100gs Could you write me at mrjohnzoidberg@mailbox.org for further debugging? (I speak German so this could speed up the process for some of you). @codesalatdev has a more unique setup, so I think the latest fix won't help for all of you.

Anyway there is a new nightly with a new version of the webkit library (which is responsible for Home Assistant connection), so maybe you can test it and write me the result in an email. Thanks!

**Comment by r100gs** [comment] 2023-04-14 17:49
The nightly build from today works so fast

**Comment by dgrammlich** [comment] 2023-04-14 19:32
The current nighly build works on my phone with Home Assistant 2023.4.4.

**Comment by Niklas04** [comment] 2023-04-15 13:40
The latest nightly build seems to work great so far with Home Assistant 2023.4.4

**Comment by WHagenauw** [comment] 2023-04-16 06:23
I tried this morning to install the nightly build on my Lenovo tablet using the latest HA and latest server version of Grocy on HA. I got until the screen in the picture (i can't click on anything). When I open nightly again it is back to the login screen.
![20230416_080315](https://user-images.githubusercontent.com/80526682/232276536-3f200711-677b-4628-b927-ab2d36033980.jpg)

Wim

**Comment by kanzn** [comment] 2023-04-27 18:50
same authentification error

**Comment by jloffredo** [comment] 2023-05-10 15:47
Having the same issue

**Comment by dominiczedler** [comment] 2023-05-21 01:06
We hope the issue is done with the latest release `v3.2.0`.
Next bugfix release for some crashes is almost already.

If some of you still have issues with Home Assistant, please open a new issue as this one is long enough now.

**Closed by dominiczedler** 2023-05-21 01:06 UTC
Labels: bug
