### ISSUE TITLE
Stock entry note limited

### ISSUE THREAD

**Issue by Saturo78** [patzly/grocy-android#600] opened 2022-12-17 22:01 UTC
The stock entry note is limited to 10 letters.
On the Grocy Website it is possible to enter more than 10 letters in the note field.

**Comment by MrJohnZoidberg** [comment] 2022-12-20 21:35
Thanks! That's a duplicate of #577. Will be fixed in the next release or you can already see the change in the current nightly build.

**Comment by Saturo78** [comment] 2022-12-20 22:34
Hi there, where i can find the latest nightly? I have installed the nightly build from github released in October and there the issue isn´t fixed.

**Comment by MrJohnZoidberg** [comment] 2022-12-24 02:06
The latest build is always [here](https://github.com/patzly/grocy-android/releases/tag/nightly). The release date of the nightly section was October but the APK is updated every night.

I think you mean the stock entry field on the purchase and inventory page in your description. If you mean another page where the field still has a limitation, please tell me.

**Closed** 2022-12-25 15:23 UTC
Labels: duplicate
