### ISSUE TITLE
Allow self-signed certificates or use imported user certificates

### ISSUE THREAD

**Issue by kaikli** [patzly/grocy-android#250] opened 2020-11-27 23:07 UTC
Give the ability to accept untrusted certificates manually, or use the imported user certificates from android.

**Comment by MrJohnZoidberg** [comment] 2020-11-28 23:06
Duplicate of #15. This feature is implemented since a few weeks and the issue is closed, but we still did not release the new version of our app yet.

**Comment by nousernameavailableanymore** [comment] 2020-12-27 20:21
In which version of the android app will self-signed certificates be supported?
When is this future version planned to be released?

**Comment by MrJohnZoidberg** [comment] 2020-12-27 20:26
User Certificates which are in the Android user certificate store should work since `v1.10.0`. You can see that if you read the changelogs.

**Comment by nousernameavailableanymore** [comment] 2020-12-27 21:10
Hmmm, I have a domain set up with mydomain.local.
DNS A-record created for grocy.mydomain.local
I exported the self-signed certificate and imported it in Android.
However, since Android ridiculously refuses to do what it is told (resolve an unknown DNS name via the DNS server which it is given and not via a DNS server which it thinks should be correct), I need to use the IP of my grocy instance.

So on the first login screen, I provide:
https://<IP_to_my_grocy>:9284
and a valid API-key.

However, I am told that no connection can be established ("connection to https://<IP_to_my_grocy>:9284 failed"), although the browser login, using the same IP works perfectly fine after I acknowledged the self-signed certificate.

So is there any way to convince the app to connect the same way the browser does (the http connection works, but I would prefer https of course).

**Comment by MrJohnZoidberg** [comment] 2020-12-27 21:25
Mmh, that's the same behavior like I experienced one or two months ago when I implemented this. Like you can read in #125 I couldn't get it working but @murizorun wrote that the implementation works for his setup...
I think there is a certificate issue (I saw certificate error messages in my console) but I cannot say more because I don't have much knowledge in this topic. Maybe murizorun can help you a little bit but he also wrote that he only followed a step by step manual for the certificate creation (which you can find in #125). :-)

I will open this issue again, as a reminder for me to test this again. But I'm afraid I won't work on that for the next weeks, because I have to finish the new `v2.0.0` of our app which is more important currently.

**Comment by murizorun** [comment] 2020-12-31 17:02
hey @nousernameavailableanymore, 

Grocy-android still implements standard TLS verification mechanism, that means that your certificate still needs to be a valid one: have Subject or SAN (Subject Alternative Name) list with valid domain you try to access it, within validation period, should be generated as a server certificate, all that TLS things.

The change implemented here, as in other android apps, is to trust also valid certificates from the Android's User Store, or however it's called.

I think in your case, the certificate is not valid for your IP subject. You should generate it with the IP in a SAN (https://en.wikipedia.org/wiki/Subject_Alternative_Name) attribute on the certificate.

My case involves creating a PKI (https://en.wikipedia.org/wiki/Public_key_infrastructure) where I trust a self-signed CA and import that to the Android User Store. This CA signs my Grocy server certificate and other LAN certificates which get trusted by how TLS works ;).

Also, take care when you resolve DNS with .local domain, as since some time it is reserved for some services to autodiscover themselves without the need of a DNS server (https://en.wikipedia.org/wiki/.local). I would recomand you switch to something else. See https://en.wikipedia.org/wiki/Special-use_domain_name for other special domains.

Hope this helps. I'll try to suport on this ticket if you have more info about how this works.

Cheers!

**Closed** 2021-02-15 19:59 UTC
Labels: duplicate

**Comment by igor-cali** [comment] 2022-04-16 15:09
> I think in your case, the certificate is not valid for your IP subject. You should generate it with the IP in a SAN (https://en.wikipedia.org/wiki/Subject_Alternative_Name) attribute on the certificate.

I'm not the issue opened. I was able to connect to my fixed-ip/no-domain personal server using the int above. I recreated the certificate adding the IP as ASN. I could not login manually entering the data, but using the barcode generated by the Grocy server worked.
